export {default as helldiversImage} from './helldivers.jpeg'
export {default as adviceSuperEarthImage} from './advice-super-earth.jpg'
export {default as berserkerImage} from './berserker.png'
export {default as commisaryImage} from './commisary.png'
export {default as enlistTodayImage} from "./enlist-today.png"
export {default as helldiversSaluteGif} from './helldivers-salute.gif'
export {default as helldiversSaluteAdviceImage}  from './helldivers-salute-advice.jpg'
export {default as hulkImage} from './hulk.png'
export {default as logoImage} from "./logo.png"
export {default as missionAccomplishedImage} from "./mission-accomplished.jpeg"
export {default as striderImage} from "./strider.png"
